---
title: "Introduction to Probability"
author: "Dr. Babak Shahbaba"
output: 
  xaringan::moon_reader:
    css: ["slide-style.css"]
    lib_dir: libs
    seal: false
    nature:
      ratio: 16:9
      highlightStyle: "pygments"
      highlightLines: true
      highlightLanguage: "r"

---

class: title-slide

```{r echo = FALSE}
library(fabricerin)
```

<br>
<br>
.right-panel[ 
<br>

# `r rmarkdown::metadata$title`

## `r rmarkdown::metadata$author`

]

---

## Introduction
 - We have used plots and summary statistics to learn about the distribution of variables and to investigate their relationships. 
 
 - We now want to generalize our findings to the population. 
 
 - However, we almost always remain uncertain about the true distributions and relationships in the population.
 
 - Therefore, when we generalize our findings from a sample to the whole population, we should explicitly specify the extent of our uncertainty.  
 
 - We now discuss probability as a measure of uncertainty.
 
 - We use some examples from genetics.  
 
---
 
## Some Commonly Used Genetic Terms
 
- Gene

- Single Nucleotide Polymorphisms (SNPs)

- Alleles

- Genotype

- Homozygous vs. heterozygous

- Phenotype

- Recessive vs. dominant

---

## Random phenomena and their sample space

- A phenomenon is called random if its outcome (value) cannot be determined with certainty before it occurs. 

- For example, coin tossing and genotypes  are random phenomena.

- The collection of all possible outcomes $S$ is called the sample space. 

  - Coin tossing: S=\{H, T\} 
  - Die rolling: S=\{1, 2, 3, 4, 5, 6\} 
  - Bi-allelic gene: S=\{A, a\} 
  - Genotype: S=\{AA, Aa, aa\}

---

## Probability

- To each possible outcome in the sample space, we assign a probability
$P$, which represents how certain we are about the occurrence of the corresponding outcome. 

- For an outcome $o$, we denote the probability as $P(o)$, where $0 \le P(o) \le 1$. 

- The total probability of all outcomes in the sample space is always 1.

  - Coin tossing: P(H)+ P(T)=1
  - Die rolling:  P(1)+P(2)+P(3)+P(4)+P(5)+P(6) = 1.


